### ISSUE TITLE
[Security] Threat model

### ISSUE THREAD

**Issue by realeroberto** [immuni-app/immuni-documentation#109]
Is a formal threat model under development? Immuni being a de facto strategic asset for Italy, it would be great if the development team or, even better, a third party could provide one.

@eutopian-eu

**Comment by PastNullInfinity** [comment]
As of now, in these repos the only formal discussion of threat modeling is in the context of data integrity and protection of data in-flight (and mitigations against Repudiation, or otherwise analysis of data by a third party via side channels or traffic analysis), as outlined by [their Application Security Description](https://github.com/immuni-app/immuni-documentation/blob/master/Application%20Security%20Description.md) and [measures for traffic analysis mitigation](https://github.com/immuni-app/immuni-documentation/blob/master/Traffic%20Analysis%20Mitigation.md).

I concur in the fact that a proper formalization of the threat model would be interesting to look at, especially because of the sensitive nature of the application, and the peculiarities of the Exposure Notification framework's threat model.
