### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by gvdr** [immuni-app/immuni-documentation#13]
In the documentation you announce that:

"The app is available in Italian, German, and British English".

The choice seems (1) arbitrary and (2) discriminatory. Without an adequate multilingual coverage, the app would not reach a large part of the Italian population, especially in particularly vulnerable sector of society, and thus jeopardize its efficiency. Looking at the linguistic composition of the migrant population in Italy, at least Arabic and Chinese should be prioritized.

**Comment by Whoenon** [comment]
Also many Northern Regions (such Trentino and Valle d'Aosta) use German as a common language, so it would be better to add that option
[https://en.wikipedia.org/wiki/List_of_territorial_entities_where_German_is_an_official_language#Other_legal_statuses](url)

**Comment by amefad** [comment]
I agree. If British english was arbitrary choosen as a common language for stranger people in Italy add at least French, used in large part of African countries

**Comment by cortesimone** [comment]
Releasing the code opensource would allow the community to collaborate in an effort to cover those languages deemed not worthy to be included in the initial plan. Useful info on [Wikipedia: Languages of Italy](https://en.wikipedia.org/wiki/Languages_of_Italy)

**Comment by amefad** [comment]
Even before releasing the code, it can be sufficient to publish interfaces strings in a collaborative platform like [transifex](https://www.transifex.com/) to start translation.

**Comment by xb8** [comment]
add romanian and slovene languages too, which are popular foreign languages

**Comment by Cesidio80** [comment]
Spanish language absolutely

**Comment by Sasso0101** [comment]
For the slovenian translations you can maybe ask [Friuli Venezia Giulia's slovene dept](http://www.regione.fvg.it/rafvg/cms/RAFVG/cultura-sport/patrimonio-culturale/comunita-linguistiche/FOGLIA25/1_pravni_okvir.html), who helps public authorities translate their stuff to slovenian. They have a [team of translators](http://www.regione.fvg.it/rafvg/cms/RAFVG/cultura-sport/patrimonio-culturale/comunita-linguistiche/FOGLIA25/4_prevajanje_in_tolmacenje.html) and I'm sure they're willing to help.

**Comment by AndreazLattmann** [comment]
In my opinion, you have never participated in a FLOSS project in your life. 
Here there are not only people who ask, there are people ready to help in the project.

**Comment by gvdr** [comment]
I don't know who your comment is addressed, @AndreazLattmann, but its tone is absolutely not helpful. Please be kind to anybody, some people may not have experience in FLOSS and their opinion is still relevant and important.

**Comment by Sasso0101** [comment]
> (deleted comment) Here there are not only people who ask, there are people ready to help in the project.

@AndreazLattmann, I'm assuming you're referring to my comment, so I'll try to explain my point a bit more in depth. As other users proposed, I think that crowdsourcing the translations is a very good idea, since the goal is to make it available to as many people as possible, but given that the Slovenian minority has already an official translation team maintained by the government (and paid by taxpayers money) I think it would be more straightforward and faster asking them, rather than waiting for someone to translate the strings and having to trust others to check the correctness and accuracy of the translations. Of course, as I said earlier one thing does not exclude the other, especially if the goal is to translate the app into as many languages as possible.
I hope my proposal is a little bit clearer now :)

**Comment by fernetmatt** [comment]
Ci fa proprio schifo la nostra lingua.. LOL

**Comment by ajanes** [comment]
If needed, I happily translate to German!

**Comment by drumbsd** [comment]
Aggiungerei anche il napoletano, il pugliese, il siciliano, il calabrese, il veneto e il friulano a questo punto.
