### ISSUE TITLE
Use gender neutral language

### ISSUE THREAD

**Issue by macteo** [immuni-app/immuni-documentation#22]
The app mockups are referring multiple times to the person using the app as a Male.

Please rephrase the occurrences to acknowledge the existence of women and non-binary people.

I.E.

> Benvenuto

Ciao

> Rilevato contatto con un positivo al COVID-19

Rilevato contatto con una persona positiva al COVID-19

**Comment by xb8** [comment]
Benvenuto (utente)
rilevato contatto con un (utente) positivo al covid-19

it has nothing to do with gender

**Comment by gianvitofanelli** [comment]
Totally agree. There’s room for improvement on how digital products deal with people. Would you ever say “Welcome user” in a real conversation? Digital products are real and their voice and character can influence positively or negatively our relationship with them. Count on me if you need any help 😊

**Comment by unbranched** [comment]
I see this "non-binary" madness is well spread nowadays.

Signed by a cat.

**Comment by gianvitofanelli** [comment]
Don't call it "madness". I'm not among those who use * in the end of words. 

What I think is that, especially in this case, the app is meant to speak to a vast population, and being as neutral as possible is right and easy to achieve. So why not? Without considering how beneficial can be the proper setting of a conversation between people and the app for the relationship between them. 

Issues concerning how digital products relate to us are costantly being raised, with reasons. Just an example: why are voice assistants always female?

**Comment by gianvitofanelli** [comment]
What I think is that, especially in this case, the app is meant to speak to a vast population, and being as neutral as possible is right and easy to achieve. So why not? Without considering how beneficial can be the proper setting of a conversation between people and the app for the relationship between them.

Issues concerning how digital products relate to us are costantly being raised, with fair reasons. Just an example: why are voice assistants always female?

**Comment by xb8** [comment]
a generic welcome user is already as neutral as possible and i fail to see how it is not

**Comment by gianvitofanelli** [comment]
I think that "user" is very depersonalizing and passive, and it doesn't keep to account that we are dealing with people and their emotions. Especially in a delicate context like an app born to deal with a pandemic, being aware and recognizing that we are speaking to people, by effectively speaking as they are people (male, female, or other), would set a better context for the conversation between the app and people.

I understand that this could sound naive, as it could sound naive being concerned about female-only voice assistants and the impact on people's education of using of the imperative verbs to talk with then. But I can assure you that brands are dealing with this kind of questions nowadays, so why governments shouldn't?

**Comment by xb8** [comment]
because brands dont have to deal with a pandemic and the privacy of ideally the whole population in a critical short time frame in which developing a reliable application is more important than the UI being gender neutral (which already is, just a bit aloof if anything). we shouldn't be discussing if "benvenuto utente" is too formal/cold when there are open issues much more concerning about how the app works we should focus on

**Comment by gianvitofanelli** [comment]
There are different people involved in a design process. Issues concerning privacy or technological aspects are not dealt by the same people who write content. Of course, the team will prioritize the issues. No one here is telling that the language issue should be the most important. Just putting a spotlight because it is often forgotten or undervalued.

By the way, if you are not interested in this topic, you are free to ignore it.

**Comment by unbranched** [comment]
I agree that a software can always be improved in communication with the user (sorry, person), but sometimes you rise a problem where there are none.
If the developer wants to greet the user with a Welcome, and you don't know who you're speaking to, then in italian it's "Benvenuto". No space for discussion.

If the italian language wants the male word for neutral audience, then this is it.

Sometimes you can find a different word to say the same thing, I have nothing against it. But "Ciao" is not the same of "Benvenuto".

**Comment by xb8** [comment]
> If the developer wants to greet the user with a Welcome, and you don't know who you're speaking to, then in italian it's "Benvenuto". No space for discussion.
> 
> If the italian language wants the male word for neutral audience, then this is it.


this. there is no problem regarding gender to begin with

**Comment by gianvitofanelli** [comment]
Writing copy should not developers’ task, indeed. Translation is not a 1:1 job, otherwise professional translators would have been substituted by algorithms years ago. Language is recognizing context and cultural differences. For instance, English nouns don’t have genders typically, they’re neutral per se, so the issue doesn’t emerge as it does in Italian.

We are here to help and contribute. I don’t want this to be no. 1 issue on the design team agenda. I just agree that this is a part of the experience that can be improved.

Have a nice day

**Comment by gvdr** [comment]
If you don't understand the issue with using non-gender neutral language, I doubt you are qualified to comment on the topic. This app needs to win the trust of the widest portion of our society. Using a language that discriminate against somebody, is not the way of doing this.

If your experience is in coding quiz apps, maybe this subtlety is lost on you.

**Comment by xb8** [comment]
it seems you fail to see how the language used is not discriminatory at all in the first place

**Comment by gvdr** [comment]
What would be, exactly, the problem in using a more gender neutral language? If it's just your personal taste, I still believe the all should strive as much as possible to be inclusive.

**Comment by xb8** [comment]
its not a problem. the point is that it is already doing so. 
you can either look at it being "benvenuto utente", which while a bit distant is as neutral as possible but also look at it as neutral, which happens in italian and many other languages is incorporated in the male nouns

discussing that "welcome" is discriminatory is just nosense

**Comment by marcosinigaglia** [comment]
I don't think is a place to discuss about gender, @xb8 if you don't see a problem in this issue don't comment please, someone else will decide.

**Comment by xb8** [comment]
why are yall telling people to stop commenting only because they dont agree with you? this matter is important to me as it is to others and im 100% down to be inclusive to everyone. point is that welcoming a user already is neutral and not discriminatory and it is counterproductive when people try to create a problem when there is none

**Comment by ali-ce** [comment]
Sorry @xb8 but the "Benvenuto utente" is not so neutral as you say. It is masculine of the feminine "Benvenuta utente", as you surely know.  And "con un (utente) positivo" is the masculine of "con un'utente positiva". 

So you are making a choice of using male as default for human. This could maybe be somehow acceptable in a phrase if there were really no alternative at all, if you showed effort for gender balance everywhere else... but this is not the case. The proposed "con una persona positiva" is perfect and then purposely refusing to use it, to adopt instead the masculine as default, is a non-inclusive approach without question.

**Comment by xb8** [comment]
that is even more discriminatory than just a generic **neutral** "benvenuto" (which again, is **not** referred to males only) against non binary people when the interface only has male and female welcoming messages

**Comment by ali-ce** [comment]
Please reread: I am not suggesting to use Benvenuta. But I am happy to see that you consider "Benvenuta" as not inclusive: that way the mental step for you to recognize that also Benvenuto is not inclusive should be logical.

**Comment by gianvitofanelli** [comment]
> that is even more discriminatory than just a generic **neutral** "benvenuto" (which again, is **not** referred to males only) against non binary people when the interface only has male and female welcoming messages

In fact, we are proposing neither to use "Benvenuto" nor "Benvenuta", so being completely neutral (es. "Ciao" works pretty well as a welcoming message in Italian).

**Comment by marcosinigaglia** [comment]
@xb8 I'm sorry to be rude but this is not a forum, the issue is clear and to me is clear that you don't understand the topic, if you want we can talk for hours about it in other an other place.

**Comment by xb8** [comment]
it seems clear to me that im vocal about it but there are plenty of people that dont agree on the subject of welcome being a bad choice, since many have reacted negatively to OP post in both this issue and the 23 one. also @unbranched has posted similar valid points against the issues so no, silencing others is not the right thing to do

**Comment by gianvitofanelli** [comment]
No one is trying to silence you ;)

Alice showed that you the Italian word "utente" is both male and female. So "Benvenuto utente" works only for males, while "Welcome user" works for all genders because the English word "Welcome" is completely neutral per se.

This is a fact; it's not our opinion.

Because of creating a dynamic interface that fits people gender would be:
1) ontologically wrong as there are people who don't recognize in both male and female genders;
2) an unecessary feature technically speaking,

we propose to use neutral forms that are available in Italian.

It requires very small adjustments that would improve the inclusivity of the app and its way of relating to people.

Edit: I'll attach here a good read on the topic: https://careerfoundry.com/en/blog/ux-design/design-for-every-gender/#1-what-is-inclusive-design-and-why-consider-gender

**Comment by FlaWister** [comment]
Agree with GianvitoFanelli:
- Persona (instead of uomo/donna) includes everybody
- Bevenuto/a utente (is not difficult to add)
