### ISSUE TITLE
Is this Github project still alive?

### ISSUE THREAD

**Issue by ivanvisconti** [immuni-app/immuni-documentation#55]
This issue has the only purpose to check whether the team members of Immuni-app are still interested in discussing issues and the development of the Immuni-app is still in progress.

**Comment by immuniopensource** [comment]
Dear @ivanvisconti, thanks for checking in and apologies for having been quite unresponsive since we published the docs about a week ago. Not an excuse, but an explanation: we have been literally working day and night to finalize the documentation (a lot more is coming soon) and get to a point where the code can be published (also happening soon). We expect to start responding to all the Issues within the next few days.

**Comment by ivanvisconti** [comment]
Thanks.
